### ISSUE TITLE
Null-safety in stable

### ISSUE THREAD

**Issue by Alex-A4** [angulardart/angular#1955]
Hey!
Are there any plans to move null-safety to stable?
I see null-safety on google branch of repo, is it ready for production?

**Comment by kevin-lot** [comment]
> Hey!
> Are there any plans to move null-safety to stable?
> I see null-safety on google branch of repo, is it ready for production?

In the README: https://groups.google.com/a/dartlang.org/g/announce/c/Kz84KNBcf3U ;)

But I'm not agree with "strongly encourage you to consider Flutter" because I considerer it is not very stable for the web even in 2.0 (and flutter for web is not compatible with Internet Explorer).

**Comment by insinfo** [comment]
@kevin-lot 

I am a passionate developer for AngularDart, and I also use Flutter for mobile development, I also don’t agree with

"strongly encourage you to consider Flutter"

I believe that Flutter can never completely replace AngularDart because the flutter does not support first class support for WEb technologies like HTML and CSS which is extremely productive in the web scenario.

**Comment by insinfo** [comment]
@krel024 
I have used AngularDart a lot with dart 2.12 and it has worked very well for me without the null security, I have not missed it

**Comment by insinfo** [comment]
@KevinBLT 
I totally agree with you

**Comment by hassansaleh31** [comment]
I have to upgrade our web app to the latest version of angular because we have some shared code between our mobile apps written in Flutter and our Web apps written in angular dart.

We're currently migrating the shared package to null safety and our mobile apps to Flutter 2.0 but now the web apps require a new version of angular with updated dependencies to work with the shared package.

I checked the master branch on this repo and it has all the upgraded dependencies I need so I tried to do this:

```yaml
  angular:
    git:
      url: git@github.com:angulardart/angular.git
      ref: master
      path: angular
  angular_forms:
    git:
      url: git@github.com:angulardart/angular.git
      ref: master
      path: angular_forms
  angular_router:
    git:
      url: git@github.com:angulardart/angular.git
      ref: master
      path: angular_router
```

But I got the following error:

```
Resolving dependencies...
Because every version of angular_router from git depends on angular from hosted and **** depends on angular from git, angular_router from git is forbidden.
So, because **** depends on angular_router from git, version solving failed.
exit code 1
```

Anyone has a valid workaround?
